# Generated by Django 3.2.8 on 2021-10-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='social_facebook',
        ),
    ]
